version: '3'
services:
  cfm:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports: 
        - 8080:8080
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done" 